# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16346d0f371c223d19f5bbc4b32717dd9266b2263c774eb6b3541da6acfffbb24611db9c6c72f89322221988325e2098fdda89ec4b7f04e00417bb93515b58e9

test:
  secret_key_base: 3202e4583edae286aa7e6b105f9057ea05eace2cc4f44893d58c1fa7c34886edfcbb29eb493eea3cba5ed84512bbffcb8c6d3246d0bcede36579bdf1c3fa1f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
